"""add fullname column to admin_profiles table

Revision ID: 2e7e7edec15e
Revises: 5b857b4a2e4c
Create Date: 2026-10-04 17:51:22.701892

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e7e7edec15e"
down_revision: str | Sequence[str] | None = "5b857b4a2e4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fullname", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_profiles", schema=None) as batch_op:
        batch_op.drop_column("fullname")

    # ### end Alembic commands ###
