"""Add new table admin_tokens

Revision ID: d83393f0361c
Revises: 2e7e7edec15e
Create Date: 2026-10-06 11:47:08.566019

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from src.models.types import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "d83393f0361c"
down_revision: str | Sequence[str] | None = "2e7e7edec15e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_tokens",
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_tokens", schema=None) as batch_op:
        batch_op.create_index(
            "ix_admin_token_expires", ["admin_id", "expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_tokens_admin_id"), ["admin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_tokens_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_tokens_token_hash"), ["token_hash"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_admin_tokens_expires_at"))
        batch_op.drop_index(batch_op.f("ix_admin_tokens_admin_id"))
        batch_op.drop_index("ix_admin_token_expires")

    op.drop_table("admin_tokens")
    # ### end Alembic commands ###
