"""create all tables

Revision ID: dc9b10c40f1a
Revises:
Create Date: 2026-10-03 18:01:39.618099

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from src.models.types import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "dc9b10c40f1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_profiles",
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "schedule_images",
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.Column("is_local", sa.Boolean(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mtime", sa.Float(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="dayofweek",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedule_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_images_file_hash"), ["file_hash"], unique=False
        )
        batch_op.create_index("ux_schedule_image_image", ["image"], unique=True)
        batch_op.create_index(
            "ux_schedule_image_local_name",
            ["name"],
            unique=True,
            sqlite_where=sa.text("is_local = 1 AND is_active = 1"),
        )

    op.create_table(
        "schedule_tables",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="dayofweek",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_columns",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("header", sa.String(length=255), nullable=False),
        sa.Column("schedule_table_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_table_id"], ["schedule_tables.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number", "schedule_table_id"),
    )
    op.create_table(
        "lessons",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schedule_column_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_column_id"], ["schedule_columns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number", "schedule_column_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lessons")
    op.drop_table("schedule_columns")
    op.drop_table("schedule_tables")
    with op.batch_alter_table("schedule_images", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_schedule_image_local_name",
            sqlite_where=sa.text("is_local = 1 AND is_active = 1"),
        )
        batch_op.drop_index("ux_schedule_image_image")
        batch_op.drop_index(batch_op.f("ix_schedule_images_file_hash"))

    op.drop_table("schedule_images")
    op.drop_table("admin_profiles")
    # ### end Alembic commands ###
