"""unique constraint for ScheduleImage.image

Revision ID: f2c3cf76a34d
Revises: 6cfaef92fded
Create Date: 2026-09-24 10:30:53.957180

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2c3cf76a34d"
down_revision: str | Sequence[str] | None = "6cfaef92fded"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.alter_column(
            "schedule_column_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    with op.batch_alter_table("schedule_columns", schema=None) as batch_op:
        batch_op.alter_column(
            "schedule_table_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    with op.batch_alter_table("schedule_images", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )
        batch_op.drop_index(
            batch_op.f("ux_schedule_image_local_image"),
            sqlite_where=sa.text("is_local = 1 AND is_active = 1"),
        )
        batch_op.create_index("ux_schedule_image_image", ["image"], unique=True)

    with op.batch_alter_table("schedule_tables", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_tables", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("schedule_images", schema=None) as batch_op:
        batch_op.drop_index("ux_schedule_image_image")
        batch_op.create_index(
            batch_op.f("ux_schedule_image_local_image"),
            ["image"],
            unique=1,
            sqlite_where=sa.text("is_local = 1 AND is_active = 1"),
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("schedule_columns", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )
        batch_op.alter_column(
            "schedule_table_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )

    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )
        batch_op.alter_column(
            "schedule_column_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
